package com.liang.sensitive.dao;


import com.liang.sensitive.pojo.countlog.CountLog;
import com.liang.sensitive.pojo.countlog.CountLogCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CountLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_count_log
     *
     * @mbg.generated
     */
    long countByExample(CountLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_count_log
     *
     * @mbg.generated
     */
    int deleteByExample(CountLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_count_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_count_log
     *
     * @mbg.generated
     */
    int insert(CountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_count_log
     *
     * @mbg.generated
     */
    int insertSelective(CountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_count_log
     *
     * @mbg.generated
     */
    List<CountLog> selectByExample(CountLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_count_log
     *
     * @mbg.generated
     */
    CountLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_count_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CountLog record, @Param("example") CountLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_count_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CountLog record, @Param("example") CountLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_count_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CountLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_count_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CountLog record);
}