package com.liang.sensitive.dao;


import com.liang.sensitive.pojo.keyword.Keyword;
import com.liang.sensitive.pojo.keyword.KeywordCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface KeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_keyword
     *
     * @mbg.generated
     */
    long countByExample(KeywordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_keyword
     *
     * @mbg.generated
     */
    int deleteByExample(KeywordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_keyword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_keyword
     *
     * @mbg.generated
     */
    int insert(Keyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_keyword
     *
     * @mbg.generated
     */
    int insertSelective(Keyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_keyword
     *
     * @mbg.generated
     */
    List<Keyword> selectByExample(KeywordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_keyword
     *
     * @mbg.generated
     */
    Keyword selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_keyword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Keyword record, @Param("example") KeywordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_keyword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Keyword record, @Param("example") KeywordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Keyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Keyword record);

    /**
     * 根据userId查询自定义的关键词，不分页
     * @param userId
     * @return
     */
    List<String> findByUserId(String userId);


}