package com.liang.admin.dao;

import com.liang.admin.pojo.sensitive.stopword.Stopword;
import com.liang.admin.pojo.sensitive.stopword.StopwordCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StopwordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_stopword
     *
     * @mbg.generated
     */
    long countByExample(StopwordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_stopword
     *
     * @mbg.generated
     */
    int deleteByExample(StopwordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_stopword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_stopword
     *
     * @mbg.generated
     */
    int insert(Stopword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_stopword
     *
     * @mbg.generated
     */
    int insertSelective(Stopword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_stopword
     *
     * @mbg.generated
     */
    List<Stopword> selectByExample(StopwordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_stopword
     *
     * @mbg.generated
     */
    Stopword selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_stopword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Stopword record, @Param("example") StopwordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_stopword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Stopword record, @Param("example") StopwordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_stopword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Stopword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_stopword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Stopword record);

    /**
     * 根据用户id查找跳过词
     * add by liang
     */
    List<Character> selectByUserId(String userId);
}